import type { Signal, Strategy, DashboardStats } from '@/types'

export const MOCK_STRATEGIES: Strategy[] = [
  {
    id: 'wick_rejection',
    name: 'Wick Rejection',
    description: 'Identifies price rejection at key levels using long wicks — high-probability reversal setups',
    active: true,
    winRate: 0.72,
    totalSignals: 148,
    avgRR: 2.4,
  },
  {
    id: 'breakout',
    name: 'Breakout',
    description: 'Detects consolidation breakouts with volume confirmation for momentum trades',
    active: true,
    winRate: 0.61,
    totalSignals: 93,
    avgRR: 2.8,
  },
  {
    id: 'trend_following',
    name: 'Trend Following',
    description: 'Rides established trends using EMA crossovers and ADX confirmation',
    active: false,
    winRate: 0.68,
    totalSignals: 211,
    avgRR: 1.9,
  },
  {
    id: 'supply_demand',
    name: 'Supply & Demand',
    description: 'Zones of institutional order flow — buy at demand, sell at supply',
    active: true,
    winRate: 0.75,
    totalSignals: 87,
    avgRR: 3.1,
  },
  {
    id: 'scalping',
    name: 'Scalping',
    description: 'High-frequency short-term signals on lower timeframes for quick entries',
    active: false,
    winRate: 0.58,
    totalSignals: 432,
    avgRR: 1.4,
  },
]

export const MOCK_SIGNALS: Signal[] = [
  {
    id: 'sig_001',
    strategy_id: 'wick_rejection',
    user_id: 'user_001',
    signal: 'BUY',
    symbol: 'EURUSD',
    confidence: 0.87,
    reason: [
      'Bullish wick rejection at 1.08200 support',
      'RSI oversold at 31.4',
      'Higher timeframe confluence (4H uptrend)',
    ],
    entry: 1.08245,
    sl: 1.08100,
    tp: 1.08590,
    rr_ratio: 2.38,
    timeframe: '1H',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_002',
    strategy_id: 'supply_demand',
    user_id: 'user_001',
    signal: 'SELL',
    symbol: 'GBPUSD',
    confidence: 0.81,
    reason: [
      'Price entered supply zone at 1.26800',
      'Bearish engulfing candle pattern',
      'Previous resistance turned rejection',
    ],
    entry: 1.26820,
    sl: 1.26980,
    tp: 1.26340,
    rr_ratio: 3.0,
    timeframe: '4H',
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_003',
    strategy_id: 'breakout',
    user_id: 'user_001',
    signal: 'BUY',
    symbol: 'USDJPY',
    confidence: 0.74,
    reason: [
      'Clean breakout above 150.50 resistance',
      'Volume spike confirms momentum',
      'Retested breakout level — valid entry',
    ],
    entry: 150.620,
    sl: 150.350,
    tp: 151.350,
    rr_ratio: 2.7,
    timeframe: '1H',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_004',
    strategy_id: 'trend_following',
    user_id: 'user_001',
    signal: 'SELL',
    symbol: 'XAUUSD',
    confidence: 0.69,
    reason: [
      'EMA 50 crossed below EMA 200 (death cross)',
      'ADX above 25 — strong bearish trend',
      'Lower highs structure confirmed',
    ],
    entry: 2015.40,
    sl: 2024.00,
    tp: 1989.50,
    rr_ratio: 2.98,
    timeframe: '4H',
    timestamp: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_005',
    strategy_id: 'wick_rejection',
    user_id: 'user_001',
    signal: 'BUY',
    symbol: 'AUDUSD',
    confidence: 0.79,
    reason: [
      'Wick rejection at 0.64500 demand zone',
      'MACD histogram turning positive',
      'Daily level aligns with entry',
    ],
    entry: 0.64540,
    sl: 0.64380,
    tp: 0.64920,
    rr_ratio: 2.38,
    timeframe: '15m',
    timestamp: new Date(Date.now() - 52 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_006',
    strategy_id: 'supply_demand',
    user_id: 'user_001',
    signal: 'NO_TRADE',
    symbol: 'NZDUSD',
    confidence: 0.42,
    reason: [
      'Price between zones — no clear level',
      'Conflicting signals on multiple timeframes',
      'Low volume session — avoid choppy conditions',
    ],
    entry: 0.60120,
    sl: 0.59900,
    tp: 0.60450,
    rr_ratio: 1.5,
    timeframe: '1H',
    timestamp: new Date(Date.now() - 68 * 60 * 1000).toISOString(),
  },
  {
    id: 'sig_007',
    strategy_id: 'breakout',
    user_id: 'user_001',
    signal: 'SELL',
    symbol: 'USDCAD',
    confidence: 0.83,
    reason: [
      'Breakout below 1.35800 key support',
      'Bank level order flow detected',
      'Momentum continuation pattern',
    ],
    entry: 1.35740,
    sl: 1.35960,
    tp: 1.35080,
    rr_ratio: 3.0,
    timeframe: '4H',
    timestamp: new Date(Date.now() - 94 * 60 * 1000).toISOString(),
  },
]

export const MOCK_STATS: DashboardStats = {
  signalsToday: 7,
  weeklyWinRate: 0.71,
  activeTrades: 3,
  pnlToday: 182.40,
}
